# Generated by Django 5.0.1 on 2024-01-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
